# Generated by Django 4.1.2 on 2022-10-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.BigIntegerField(verbose_name=1)),
            ],
        ),
    ]
