# Generated by Django 4.1.2 on 2022-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('role', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('txn_dt', models.DateTimeField()),
                ('is_active', models.BooleanField(verbose_name=False)),
                ('is_blocked', models.BooleanField(verbose_name=False)),
                ('created', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
