# Generated by Django 4.1.2 on 2022-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
