# Generated by Django 4.1.2 on 2022-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_appuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
