# Generated by Django 4.1.2 on 2022-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_appuser_created_alter_appuser_txn_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='txn_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
