class AdminOperations:
    
    def create_new_customer(self):
        ...

    def list_all_customers(self):
        ...
    
    def activate_account(self):
        ...
    
    def deactivate_account(self):
        ...

    def block_account(self):
        ...
    
    def unblock_account(self):
        ...