# Generated by Django 4.1.2 on 2022-10-31 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 12, 21, 40, 494073, tzinfo=datetime.timezone.utc)),
        ),
    ]
