# Generated by Django 4.1.2 on 2022-10-31 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_appuser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 31, 12, 23, 25, 340892, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='txn_dt',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 31, 12, 23, 25, 340714, tzinfo=datetime.timezone.utc)),
        ),
    ]
